Update gki-kernel.yml

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -57,16 +57,16 @@ jobs:
             [🔗 View GitHub Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
             -F parse_mode="Markdown"
             
-      - name: Send Initial Telegram Message
-        id: send_initial_message
-        run: |
-          MESSAGE_TEXT="🚀 **GKI Kernel Build Initialized** 🚀%0A%0A*Status: Build process started...*%0A%0A*Progress:*%0A\`[□□□□□□□□□□]\` 0%%"
-          RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ env.TELEGRAM_CHAT_ID }}" -d "text=${MESSAGE_TEXT}" -d "parse_mode=Markdown")
-          MESSAGE_ID=$(echo $RESPONSE | jq -r '.result.message_id')
-          if [ -z "$MESSAGE_ID" ] || [ "$MESSAGE_ID" == "null" ]; then
-            echo "Error: Could not retrieve Telegram message ID." && exit 1
-          fi
-          echo "MESSAGE_ID=$MESSAGE_ID" >> $GITHUB_ENV
+     # - name: Send Initial Telegram Message
+      #  id: send_initial_message
+       # run: |
+       #   MESSAGE_TEXT="🚀 **GKI Kernel Build Initialized** 🚀%0A%0A*Status: Build process started...*%0A%0A*Progress:*%0A\`[□□□□□□□□□□]\` 0%%"
+       #   RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ env.TELEGRAM_CHAT_ID }}" -d "text=${MESSAGE_TEXT}" -d "parse_mode=Markdown")
+       #   MESSAGE_ID=$(echo $RESPONSE | jq -r '.result.message_id')
+       #   if [ -z "$MESSAGE_ID" ] || [ "$MESSAGE_ID" == "null" ]; then
+       #     echo "Error: Could not retrieve Telegram message ID." && exit 1
+       #   fi
+       #   echo "MESSAGE_ID=$MESSAGE_ID" >> $GITHUB_ENV
 
             
       - name: Maximize build space
